### PR TITLE
Update layout of PieMenu Preferences for better readability

### PR DESCRIPTION
**Pull request by pgilfernandez**
- Rearranged PieMenu and Global Settings items
- added a new "separator" style for all stylesheets as FreeCAD ones couldn't take care of them (as they are built with QFrames...)

### CODE REVIEW

**Comment by Grubuntu** [comment]
Very good, I try it.

I have this rendering  : 
Capture d’écran (73)


 I found a small oversight  with 'Number of columns:' alignment: 
Capture d’écran (72)

**Comment by pgilfernandez** [comment]
Great, that's the proposed layout.

> I found a small oversight with 'Number of columns:' alignment:

Yes, I overlooked that one, let me update this PR with the fix...

**Comment by pgilfernandez** [comment]
Done!

**Comment by Grubuntu** [comment]
I merged it, and I realized afterwards that the alignments will have to be reworked, because it is not consistent with the current arrangement of FreeCad menus where everything is aligned to the left.

Capture d’écran (74)
Capture d’écran (75)

**Pull request merged**
